### ISSUE TITLE
API key

### ISSUE THREAD

**Issue by Arkst0n** [xtekky/funcaptcha#2]
Where do you get the api key? For example for roblox

**Comment by Hazza3100** [comment]
@Arkst0n if you make a signup request it will most likely show, it begins with A

**Comment by bilal6622** [comment]
You need to locate two values on the page with Arkose Labs captcha

- Public key
- Service URL (surl)
Public key can be found inside data-pkey parameter of funcaptcha's div element or inside an input element with name fc-token - just extract the key indicated after pk from the value of this element.
Service Url can be also found in fc-token - that is a value of surl parameter.
